# Generated by Django 4.0.1 on 2022-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField()),
                ('complete', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
