# Generated by Django 4.0.1 on 2022-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stop_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stop_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
